variable "gcp_region" {
  type        = string
  description = "The region where the service is deployed."
}

variable "pubsub_topic_ids" {
  type        = map(string)
  description = "Map of event full name → Pub/Sub topic id, used to wire the service's triggers."
}

variable "spanner_ddl_dependency" {
  type        = list(string)
  description = "The ordering database DDL, used as a deploy-time dependency of the service."
}

variable "firestore_database" {
  type        = string
  description = "The name of the Firestore database the service writes its read model to."
}

variable "active_versions" {
  type        = map(string)
  description = "Active service versions, keyed by service name. Overrides the causa.yaml version."
}

variable "is_production" {
  type        = bool
  description = "Whether this is the production environment."
}

locals {
  # The per-project configuration JSONs, generated by the
  # ProjectWriteConfigurations processor. It contains the service's endpoints,
  # triggers, sizing, active version... everything the Cloud Run module needs.
  causa_directory                  = "${path.module}/../../../.causa"
  project_configurations_directory = "${local.causa_directory}/project-configurations"
}
