// This file was generated by the Causa command line. Do not edit it manually.

import {
  type EventAttributes as _CausaRuntimeEventAttributes,
  type ReadOnlyStateTransaction as _CausaRuntimeReadOnlyStateTransaction,
  type Transaction as _CausaRuntimeTransaction,
  type TransactionRunner as _CausaRuntimeTransactionRunner,
} from '@causa/runtime';
import {
  type AppFixture as _CausaRuntimeAppFixture,
  type EventFixture as _CausaRuntimeEventFixture,
} from '@causa/runtime/nestjs/testing';
import { VersionedEntityFixture as _CausaRuntimeVersionedEntityFixture } from '@causa/runtime/testing';
import 'jest-extended';
import {
  BookAvailability,
  BookProjection,
  Order,
  OrderBookIndex,
  OrderDocument,
  OrderEvent,
  OrderLine,
  OrderStatus,
  type OrderCancelled,
  type OrderConfirmed,
  type OrderDeleted,
  type OrderFailed,
  type OrderNotDeleted,
  type OrderPending,
  type OrderProcessing,
} from './generated.js';

export async function expectOrder(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<Order>,
): Promise<Order> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    createdAt: expect.any(Date),
    customer: expect.any(String),
    deletedAt: expect.toBeOneOf([null, expect.any(Date)]),
    externalReference: expect.toBeOneOf([null, expect.any(String)]),
    id: expect.any(String),
    lines: expect.any(Array),
    status: expect.toBeOneOf([
      OrderStatus.Pending,
      OrderStatus.Processing,
      OrderStatus.Confirmed,
      OrderStatus.Failed,
      OrderStatus.Cancelled,
    ]),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as Order;
}

export async function expectOrderNotToExist(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  key: Partial<Order>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) => t.get(Order, key));
  expect(actual).toEqual(null);
}

export async function expectOrderCancelled(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderCancelled>,
): Promise<OrderCancelled> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Cancelled,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    id: expect.any(String),
    lines: expect.any(Array),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderCancelled;
}

export async function expectOrderConfirmed(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderConfirmed>,
): Promise<OrderConfirmed> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    externalReference: expect.any(String),
    status: OrderStatus.Confirmed,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    id: expect.any(String),
    lines: expect.any(Array),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderConfirmed;
}

export async function expectOrderDeleted(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderDeleted>,
): Promise<OrderDeleted> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: expect.any(Date),
    createdAt: expect.any(Date),
    customer: expect.any(String),
    externalReference: expect.toBeOneOf([null, expect.any(String)]),
    id: expect.any(String),
    lines: expect.any(Array),
    status: expect.toBeOneOf([
      OrderStatus.Pending,
      OrderStatus.Processing,
      OrderStatus.Confirmed,
      OrderStatus.Failed,
      OrderStatus.Cancelled,
    ]),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderDeleted;
}

export async function expectOrderFailed(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderFailed>,
): Promise<OrderFailed> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Failed,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    id: expect.any(String),
    lines: expect.any(Array),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderFailed;
}

export async function expectOrderLine(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderLine>,
): Promise<OrderLine> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderLine, expected),
  );
  expect(actual).toEqual({
    book: expect.any(String),
    quantity: expect.any(Number),
    ...expected,
  });
  return actual as OrderLine;
}

export async function expectOrderLineNotToExist(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  key: Partial<OrderLine>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderLine, key),
  );
  expect(actual).toEqual(null);
}

export async function expectOrderNotDeleted(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderNotDeleted>,
): Promise<OrderNotDeleted> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    externalReference: expect.toBeOneOf([null, expect.any(String)]),
    id: expect.any(String),
    lines: expect.any(Array),
    status: expect.toBeOneOf([
      OrderStatus.Pending,
      OrderStatus.Processing,
      OrderStatus.Confirmed,
      OrderStatus.Failed,
      OrderStatus.Cancelled,
    ]),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderNotDeleted;
}

export async function expectOrderPending(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderPending>,
): Promise<OrderPending> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Pending,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    id: expect.any(String),
    lines: expect.any(Array),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderPending;
}

export async function expectOrderProcessing(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderProcessing>,
): Promise<OrderProcessing> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(Order, expected),
  );
  expect(actual).toEqual({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Processing,
    createdAt: expect.any(Date),
    customer: expect.any(String),
    id: expect.any(String),
    lines: expect.any(Array),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderProcessing;
}

export async function expectOrderEvent(
  eventFixture: _CausaRuntimeEventFixture,
  expected: Partial<OrderEvent> = {},
): Promise<void> {
  await eventFixture.expectEvent('ordering.order.v1', {
    data: expect.any(Order),
    id: expect.any(String),
    name: expect.any(String),
    producedAt: expect.any(Date),
    ...expected,
  });
}

export async function expectNoOrderEvent(
  eventFixture: _CausaRuntimeEventFixture,
): Promise<void> {
  await eventFixture.expectNoEvent('ordering.order.v1');
}

export async function expectOrderNotMutated(
  fixture: _CausaRuntimeAppFixture,
  entity: Order,
  tests: { expectNoEvent?: boolean } = {},
): Promise<void> {
  await fixture
    .get(_CausaRuntimeVersionedEntityFixture)
    .expectNoMutation(entity, {
      expectNoEventInTopic: tests.expectNoEvent
        ? 'ordering.order.v1'
        : undefined,
    });
}

export async function expectOrderCancelledEvent(
  fixture: _CausaRuntimeAppFixture,
  before: Partial<Order>,
  updates: Partial<OrderCancelled> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: _CausaRuntimeEventAttributes;
  } = {},
): Promise<Order> {
  return await fixture.get(_CausaRuntimeVersionedEntityFixture).expectMutated(
    { type: Order, entity: before },
    {
      expectedEntity: {
        deletedAt: null,
        externalReference: null,
        createdAt: expect.any(Date),
        customer: expect.any(String),
        id: expect.any(String),
        lines: expect.any(Array),
        ...before,
        status: OrderStatus.Cancelled,
        updatedAt: expect.any(Date),
        ...updates,
      },
      expectedEvent: {
        topic: 'ordering.order.v1',
        name: expect.toBeOneOf(['orderCancelled']),
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}

export async function expectOrderConfirmedEvent(
  fixture: _CausaRuntimeAppFixture,
  before: Partial<Order>,
  updates: Partial<OrderConfirmed> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: _CausaRuntimeEventAttributes;
  } = {},
): Promise<Order> {
  return await fixture.get(_CausaRuntimeVersionedEntityFixture).expectMutated(
    { type: Order, entity: before },
    {
      expectedEntity: {
        deletedAt: null,
        createdAt: expect.any(Date),
        customer: expect.any(String),
        id: expect.any(String),
        lines: expect.any(Array),
        ...before,
        externalReference: expect.any(String),
        status: OrderStatus.Confirmed,
        updatedAt: expect.any(Date),
        ...updates,
      },
      expectedEvent: {
        topic: 'ordering.order.v1',
        name: expect.toBeOneOf(['orderConfirmed']),
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}

export async function expectOrderFailedEvent(
  fixture: _CausaRuntimeAppFixture,
  before: Partial<Order>,
  updates: Partial<OrderFailed> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: _CausaRuntimeEventAttributes;
  } = {},
): Promise<Order> {
  return await fixture.get(_CausaRuntimeVersionedEntityFixture).expectMutated(
    { type: Order, entity: before },
    {
      expectedEntity: {
        deletedAt: null,
        externalReference: null,
        createdAt: expect.any(Date),
        customer: expect.any(String),
        id: expect.any(String),
        lines: expect.any(Array),
        ...before,
        status: OrderStatus.Failed,
        updatedAt: expect.any(Date),
        ...updates,
      },
      expectedEvent: {
        topic: 'ordering.order.v1',
        name: expect.toBeOneOf(['orderFailed']),
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}

export async function expectOrderPlacedEvent(
  fixture: _CausaRuntimeAppFixture,
  before: Partial<Order>,
  updates: Partial<OrderPending> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: _CausaRuntimeEventAttributes;
  } = {},
): Promise<Order> {
  return await fixture.get(_CausaRuntimeVersionedEntityFixture).expectMutated(
    { type: Order, entity: before },
    {
      expectedEntity: {
        deletedAt: null,
        externalReference: null,
        status: OrderStatus.Pending,
        createdAt: expect.any(Date),
        customer: expect.any(String),
        id: expect.any(String),
        lines: expect.any(Array),
        updatedAt: expect.any(Date),
        ...updates,
      },
      expectedEvent: {
        topic: 'ordering.order.v1',
        name: expect.toBeOneOf(['orderPlaced']),
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}

export async function expectOrderProcessingEvent(
  fixture: _CausaRuntimeAppFixture,
  before: Partial<Order>,
  updates: Partial<OrderProcessing> = {},
  tests: {
    matchesHttpResponse?: object;
    eventAttributes?: _CausaRuntimeEventAttributes;
  } = {},
): Promise<Order> {
  return await fixture.get(_CausaRuntimeVersionedEntityFixture).expectMutated(
    { type: Order, entity: before },
    {
      expectedEntity: {
        deletedAt: null,
        externalReference: null,
        createdAt: expect.any(Date),
        customer: expect.any(String),
        id: expect.any(String),
        lines: expect.any(Array),
        ...before,
        status: OrderStatus.Processing,
        updatedAt: expect.any(Date),
        ...updates,
      },
      expectedEvent: {
        topic: 'ordering.order.v1',
        name: expect.toBeOneOf(['orderProcessing']),
        attributes: tests.eventAttributes,
      },
      matchesHttpResponse: tests.matchesHttpResponse,
    },
  );
}

export async function expectOrderDocument(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderDocument>,
): Promise<OrderDocument> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderDocument, expected),
  );
  expect(actual).toEqual({
    createdAt: expect.any(Date),
    customer: expect.any(String),
    deletedAt: expect.toBeOneOf([null, expect.any(Date)]),
    id: expect.any(String),
    lines: expect.any(Array),
    status: expect.toBeOneOf([
      OrderStatus.Pending,
      OrderStatus.Processing,
      OrderStatus.Confirmed,
      OrderStatus.Failed,
      OrderStatus.Cancelled,
    ]),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as OrderDocument;
}

export async function expectOrderDocumentNotToExist(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  key: Partial<OrderDocument>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderDocument, key),
  );
  expect(actual).toEqual(null);
}

export async function expectBookProjection(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<BookProjection>,
): Promise<BookProjection> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(BookProjection, expected),
  );
  expect(actual).toEqual({
    availability: expect.toBeOneOf([
      BookAvailability.Available,
      BookAvailability.OutOfStock,
      BookAvailability.Discontinued,
    ]),
    createdAt: expect.any(Date),
    deletedAt: expect.toBeOneOf([null, expect.any(Date)]),
    id: expect.any(String),
    title: expect.any(String),
    updatedAt: expect.any(Date),
    ...expected,
  });
  return actual as BookProjection;
}

export async function expectBookProjectionNotToExist(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  key: Partial<BookProjection>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(BookProjection, key),
  );
  expect(actual).toEqual(null);
}

export async function expectOrderBookIndex(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  expected: Partial<OrderBookIndex>,
): Promise<OrderBookIndex> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderBookIndex, expected),
  );
  expect(actual).toEqual({
    book: expect.any(String),
    createdAt: expect.any(Date),
    id: expect.any(String),
    ...expected,
  });
  return actual as OrderBookIndex;
}

export async function expectOrderBookIndexNotToExist(
  runner: _CausaRuntimeTransactionRunner<
    _CausaRuntimeTransaction,
    _CausaRuntimeReadOnlyStateTransaction
  >,
  key: Partial<OrderBookIndex>,
): Promise<void> {
  const actual = await runner.run({ readOnly: true }, (t) =>
    t.get(OrderBookIndex, key),
  );
  expect(actual).toEqual(null);
}
