// This file was generated by the Causa command line. Do not edit it manually.

import { IsNullable as _CausaRuntimeIsNullable } from '@causa/runtime';
import {
  FirestoreCollection as _CausaRuntimeGoogleFirestoreCollection,
  SoftDeletedFirestoreCollection as _CausaRuntimeGoogleSoftDeletedFirestoreCollection,
  SpannerColumn as _CausaRuntimeGoogleSpannerColumn,
  SpannerTable as _CausaRuntimeGoogleSpannerTable,
} from '@causa/runtime-google';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  Equals as _ClassValidatorEquals,
  IsArray as _ClassValidatorIsArray,
  IsDate as _ClassValidatorIsDate,
  IsDefined as _ClassValidatorIsDefined,
  IsIn as _ClassValidatorIsIn,
  IsInt as _ClassValidatorIsInt,
  IsObject as _ClassValidatorIsObject,
  IsString as _ClassValidatorIsString,
  IsUUID as _ClassValidatorIsUuid,
  ValidateNested as _ClassValidatorValidateNested,
} from 'class-validator';

/**
 * Whether a book can currently be ordered.
 */
export enum BookAvailability {
  Available = 'available',
  OutOfStock = 'outOfStock',
  Discontinued = 'discontinued',
}

/**
 * A book that has been deleted.
 */
export type BookDeleted = Book & BookDeletedConstraint;

/**
 * A book that has been deleted.
 */
export class BookDeletedConstraint {
  constructor(init: BookDeletedConstraint) {
    Object.assign(this, init);
  }

  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date;
}

/**
 * An event indicating that a book was deleted.
 */
export type BookDeletedEvent = BookEvent & BookDeletedEventConstraint;

/**
 * An event indicating that a book was deleted.
 */
export class BookDeletedEventConstraint {
  constructor(init: BookDeletedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('bookDeleted')
  readonly name!: 'bookDeleted';

  @_ClassTransformerType(() => BookDeletedConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: BookDeletedConstraint;
}

/**
 * The name of a book event.
 */
export enum BookEventName {
  BookCreated = 'bookCreated',
  BookUpdated = 'bookUpdated',
  BookDeleted = 'bookDeleted',
}

/**
 * A book genre a client may set through the API.
 */
export enum BookGenre {
  Fiction = 'fiction',
  NonFiction = 'nonFiction',
  Children = 'children',
  Poetry = 'poetry',
  Comics = 'comics',
}

/**
 * A book that has not been deleted.
 */
export type BookNotDeleted = Book & BookNotDeletedConstraint;

/**
 * A book that has not been deleted.
 */
export class BookNotDeletedConstraint {
  constructor(init: BookNotDeletedConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;
}

/**
 * An event indicating that a book was created.
 */
export type BookCreatedEvent = BookEvent & BookCreatedEventConstraint;

/**
 * An event indicating that a book was created.
 */
export class BookCreatedEventConstraint {
  constructor(init: BookCreatedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('bookCreated')
  readonly name!: 'bookCreated';

  @_ClassTransformerType(() => BookNotDeletedConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: BookNotDeletedConstraint;
}

/**
 * Returned when an order references books that are not in the catalogue.
 */
export class BookNotFoundErrorDto {
  constructor(init: BookNotFoundErrorDto) {
    Object.assign(this, init);
  }

  /**
   * The HTTP status code of the error.
   */
  @_ClassValidatorEquals(400)
  readonly statusCode!: 400;

  /**
   * An error identifier, as a string.
   */
  @_ClassValidatorEquals('ordering.bookNotFound')
  readonly errorCode!: 'ordering.bookNotFound';

  /**
   * A human-readable description of the error.
   */
  @_ClassValidatorIsString()
  readonly message!: string;

  /**
   * The IDs of the books that could not be found.
   */
  @_ClassValidatorIsArray()
  @_ClassValidatorIsUuid(undefined, { each: true })
  readonly books!: string[];
}

/**
 * A local projection of catalogue `Book` entities.
 */
@_CausaRuntimeGoogleSpannerTable({ primaryKey: ['id'] })
export class BookProjection {
  constructor(init: BookProjection) {
    Object.assign(this, init);
  }

  /**
   * The unique ID of the book.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The date at which the book was added to the catalogue.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly createdAt!: Date;

  /**
   * The date at which the book was last updated.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;

  /**
   * The date at which the book was removed from the catalogue.
   */
  @_CausaRuntimeGoogleSpannerColumn({ softDelete: true })
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date | null;

  /**
   * The title of the book.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsString()
  readonly title!: string;

  /**
   * Whether the book can currently be ordered.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsIn(['available', 'outOfStock', 'discontinued'])
  readonly availability!: BookAvailability;
}

/**
 * Returned when an order references books that cannot currently be ordered.
 */
export class BookUnavailableErrorDto {
  constructor(init: BookUnavailableErrorDto) {
    Object.assign(this, init);
  }

  /**
   * The HTTP status code of the error.
   */
  @_ClassValidatorEquals(400)
  readonly statusCode!: 400;

  /**
   * An error identifier, as a string.
   */
  @_ClassValidatorEquals('ordering.bookUnavailable')
  readonly errorCode!: 'ordering.bookUnavailable';

  /**
   * A human-readable description of the error.
   */
  @_ClassValidatorIsString()
  readonly message!: string;

  /**
   * The IDs of the books that cannot currently be ordered.
   */
  @_ClassValidatorIsArray()
  @_ClassValidatorIsUuid(undefined, { each: true })
  readonly books!: string[];
}

/**
 * An event indicating that a book's details were updated.
 */
export type BookUpdatedEvent = BookEvent & BookUpdatedEventConstraint;

/**
 * An event indicating that a book's details were updated.
 */
export class BookUpdatedEventConstraint {
  constructor(init: BookUpdatedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('bookUpdated')
  readonly name!: 'bookUpdated';

  @_ClassTransformerType(() => BookNotDeletedConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: BookNotDeletedConstraint;
}

/**
 * Returned when the operation is not allowed for the order's current status.
 */
export class InvalidOrderStatusErrorDto {
  constructor(init: InvalidOrderStatusErrorDto) {
    Object.assign(this, init);
  }

  /**
   * The HTTP status code of the error.
   */
  @_ClassValidatorEquals(400)
  readonly statusCode!: 400;

  /**
   * An error identifier, as a string.
   */
  @_ClassValidatorEquals('ordering.invalidOrderStatus')
  readonly errorCode!: 'ordering.invalidOrderStatus';

  /**
   * A human-readable description of the error.
   */
  @_ClassValidatorIsString()
  readonly message!: string;
}

/**
 * A monetary amount in a single currency.
 */
export class Money {
  constructor(init: Money) {
    Object.assign(this, init);
  }

  /**
   * The amount, in minor units of the currency (e.g. cents).
   */
  @_ClassValidatorIsInt()
  readonly amount!: number;

  /**
   * The ISO 4217 currency code of the amount (e.g. EUR).
   */
  @_ClassValidatorIsString()
  readonly currency!: string;
}

/**
 * A book sold by the shop.
 */
export class Book {
  constructor(init: Book) {
    Object.assign(this, init);
  }

  /**
   * The unique ID of the book.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The date at which the book was added to the catalogue.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly createdAt!: Date;

  /**
   * The date at which the book was last updated.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;

  /**
   * The date at which the book was removed from the catalogue.
   */
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date | null;

  /**
   * The title of the book.
   */
  @_ClassValidatorIsString()
  readonly title!: string;

  /**
   * The name of the book's author.
   */
  @_ClassValidatorIsString()
  readonly authorName!: string;

  /**
   * The 13-digit ISBN-13 of the book.
   */
  @_ClassValidatorIsString()
  readonly isbn!: string;

  /**
   * The retail price of the book.
   */
  @_ClassTransformerType(() => Money)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly price!: Money;

  /**
   * The shop's acquisition cost for the book.
   * Visible to staff only.
   */
  @_ClassTransformerType(() => Money)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly cost!: Money;

  /**
   * Whether the book can currently be ordered.
   */
  @_ClassValidatorIsIn(['available', 'outOfStock', 'discontinued'])
  readonly availability!: BookAvailability;

  /**
   * The genre of the book.
   */
  @_ClassValidatorIsString()
  readonly genre!: string | BookGenre;
}

/**
 * An event describing a change to a book in the catalogue.
 */
export class BookEvent {
  constructor(init: BookEvent) {
    Object.assign(this, init);
  }

  /**
   * The UUID of the event.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The business date at which the event was produced.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly producedAt!: Date;

  /**
   * The name of the event.
   */
  @_ClassValidatorIsString()
  readonly name!: string | BookEventName;

  /**
   * The book.
   */
  @_ClassTransformerType(() => Book)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: Book;
}

/**
 * A confirmed order.
 */
export type OrderConfirmed = Order & OrderConfirmedConstraint;

/**
 * A confirmed order.
 */
export class OrderConfirmedConstraint {
  constructor(init: OrderConfirmedConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('confirmed')
  readonly status!: OrderStatus.Confirmed;

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;

  @_ClassValidatorIsString()
  readonly externalReference!: string;
}

/**
 * An event indicating that a processing order was confirmed by the third party.
 */
export type OrderConfirmedEvent = OrderEvent & OrderConfirmedEventConstraint;

/**
 * An event indicating that a processing order was confirmed by the third party.
 */
export class OrderConfirmedEventConstraint {
  constructor(init: OrderConfirmedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('orderConfirmed')
  readonly name!: 'orderConfirmed';

  @_ClassTransformerType(() => OrderConfirmedConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: OrderConfirmedConstraint;
}

/**
 * A requested line of an order.
 */
export class OrderCreateLineDto {
  constructor(init: OrderCreateLineDto) {
    Object.assign(this, init);
  }

  /**
   * The ID of the book to order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly book!: string;

  /**
   * How many copies to order.
   */
  @_ClassValidatorIsInt()
  readonly quantity!: number;
}

/**
 * The data needed to place a new order.
 */
export class OrderCreateDto {
  constructor(init: OrderCreateDto) {
    Object.assign(this, init);
  }

  /**
   * The books to order.
   * At least one line is required.
   */
  @_ClassTransformerType(() => OrderCreateLineDto)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly lines!: OrderCreateLineDto[];
}

/**
 * An order that has been deleted.
 */
export type OrderDeleted = Order & OrderDeletedConstraint;

/**
 * An order that has been deleted.
 */
export class OrderDeletedConstraint {
  constructor(init: OrderDeletedConstraint) {
    Object.assign(this, init);
  }

  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date;
}

/**
 * The name of an order event.
 */
export enum OrderEventName {
  OrderPlaced = 'orderPlaced',
  OrderProcessing = 'orderProcessing',
  OrderConfirmed = 'orderConfirmed',
  OrderFailed = 'orderFailed',
}

/**
 * An order that failed.
 */
export type OrderFailed = Order & OrderFailedConstraint;

/**
 * An order that failed.
 */
export class OrderFailedConstraint {
  constructor(init: OrderFailedConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('failed')
  readonly status!: OrderStatus.Failed;

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;

  @_ClassValidatorEquals(null)
  readonly externalReference!: null;
}

/**
 * An event indicating that an order failed.
 */
export type OrderFailedEvent = OrderEvent & OrderFailedEventConstraint;

/**
 * An event indicating that an order failed.
 */
export class OrderFailedEventConstraint {
  constructor(init: OrderFailedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('orderFailed')
  readonly name!: 'orderFailed';

  @_ClassTransformerType(() => OrderFailedConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: OrderFailedConstraint;
}

/**
 * A quantity of a single book within an order.
 */
export class OrderLine {
  constructor(init: OrderLine) {
    Object.assign(this, init);
  }

  /**
   * The ID of the ordered book.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly book!: string;

  /**
   * The number of copies ordered (at least one).
   */
  @_ClassValidatorIsInt()
  readonly quantity!: number;
}

/**
 * An order that has not been deleted.
 */
export type OrderNotDeleted = Order & OrderNotDeletedConstraint;

/**
 * An order that has not been deleted.
 */
export class OrderNotDeletedConstraint {
  constructor(init: OrderNotDeletedConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;
}

/**
 * A pending order.
 */
export type OrderPending = Order & OrderPendingConstraint;

/**
 * A pending order.
 */
export class OrderPendingConstraint {
  constructor(init: OrderPendingConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('pending')
  readonly status!: OrderStatus.Pending;

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;

  @_ClassValidatorEquals(null)
  readonly externalReference!: null;
}

/**
 * An event indicating that a new order was placed.
 */
export type OrderPlacedEvent = OrderEvent & OrderPlacedEventConstraint;

/**
 * An event indicating that a new order was placed.
 */
export class OrderPlacedEventConstraint {
  constructor(init: OrderPlacedEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('orderPlaced')
  readonly name!: 'orderPlaced';

  @_ClassTransformerType(() => OrderPendingConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: OrderPendingConstraint;
}

/**
 * An order being synchronized with the third-party system.
 */
export type OrderProcessing = Order & OrderProcessingConstraint;

/**
 * An order being synchronized with the third-party system.
 */
export class OrderProcessingConstraint {
  constructor(init: OrderProcessingConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('processing')
  readonly status!: OrderStatus.Processing;

  @_ClassValidatorEquals(null)
  readonly deletedAt!: null;

  @_ClassValidatorEquals(null)
  readonly externalReference!: null;
}

/**
 * An event indicating that a pending order started third-party synchronization.
 */
export type OrderProcessingEvent = OrderEvent & OrderProcessingEventConstraint;

/**
 * An event indicating that a pending order started third-party synchronization.
 */
export class OrderProcessingEventConstraint {
  constructor(init: OrderProcessingEventConstraint) {
    Object.assign(this, init);
  }

  @_ClassValidatorEquals('orderProcessing')
  readonly name!: 'orderProcessing';

  @_ClassTransformerType(() => OrderProcessingConstraint)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: OrderProcessingConstraint;
}

/**
 * The status of an order.
 */
export enum OrderStatus {
  Pending = 'pending',
  Processing = 'processing',
  Confirmed = 'confirmed',
  Failed = 'failed',
}

/**
 * An order placed by a customer for one or more books.
 */
@_CausaRuntimeGoogleSpannerTable({ primaryKey: ['id'] })
export class Order {
  constructor(init: Order) {
    Object.assign(this, init);
  }

  /**
   * The unique ID of the order.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The date at which the order was placed.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly createdAt!: Date;

  /**
   * The date at which the order was last updated.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;

  /**
   * The date at which the order was deleted.
   */
  @_CausaRuntimeGoogleSpannerColumn({ softDelete: true })
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date | null;

  /**
   * The ID of the customer who placed the order.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsUuid(undefined)
  readonly customer!: string;

  /**
   * The current status of the order.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_ClassValidatorIsIn(['pending', 'processing', 'confirmed', 'failed'])
  readonly status!: OrderStatus;

  /**
   * The lines of the order (at least one).
   */
  @_CausaRuntimeGoogleSpannerColumn({ isJson: true })
  @_ClassTransformerType(() => OrderLine)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly lines!: OrderLine[];

  /**
   * The reference assigned by the third-party system on confirmation.
   */
  @_CausaRuntimeGoogleSpannerColumn()
  @_CausaRuntimeIsNullable()
  @_ClassValidatorIsString()
  readonly externalReference!: string | null;
}

/**
 * An order placed by a customer for one or more books.
 */
@_CausaRuntimeGoogleFirestoreCollection({ path: (doc) => ['orders', doc.id] })
@_CausaRuntimeGoogleSoftDeletedFirestoreCollection()
export class OrderDocument {
  constructor(init: OrderDocument) {
    Object.assign(this, init);
  }

  /**
   * The unique ID of the order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The date at which the order was placed.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly createdAt!: Date;

  /**
   * The date at which the order was last updated.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;

  /**
   * The date at which the order was deleted.
   */
  @_CausaRuntimeIsNullable()
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly deletedAt!: Date | null;

  /**
   * The ID of the customer who placed the order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly customer!: string;

  /**
   * The current status of the order.
   */
  @_ClassValidatorIsIn(['pending', 'processing', 'confirmed', 'failed'])
  readonly status!: OrderStatus;

  /**
   * The lines of the order.
   */
  @_ClassTransformerType(() => OrderLine)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly lines!: OrderLine[];
}

/**
 * An event describing a change to an order.
 */
export class OrderEvent {
  constructor(init: OrderEvent) {
    Object.assign(this, init);
  }

  /**
   * The UUID of the event.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The business date at which the event was produced.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly producedAt!: Date;

  /**
   * The name of the event.
   */
  @_ClassValidatorIsString()
  readonly name!: string | OrderEventName;

  /**
   * The order.
   */
  @_ClassTransformerType(() => Order)
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject()
  @_ClassValidatorValidateNested()
  readonly data!: Order;
}

/**
 * An order as returned by the ordering API.
 */
export class OrderPublicDto {
  constructor(init: OrderPublicDto) {
    Object.assign(this, init);
  }

  /**
   * The unique ID of the order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;

  /**
   * The date at which the order was placed.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly createdAt!: Date;

  /**
   * The date at which the order was last updated. Pass back as `updatedAt` on mutations.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;

  /**
   * The customer who placed the order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly customer!: string;

  /**
   * The current status of the order.
   */
  @_ClassValidatorIsIn(['pending', 'processing', 'confirmed', 'failed'])
  readonly status!: OrderStatus;

  /**
   * The priced lines of the order.
   */
  @_ClassTransformerType(() => OrderLine)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly lines!: OrderLine[];
}

/**
 * A page of orders.
 */
export class OrderListDto {
  constructor(init: OrderListDto) {
    Object.assign(this, init);
  }

  /**
   * The orders in this page.
   */
  @_ClassTransformerType(() => OrderPublicDto)
  @_ClassValidatorIsArray()
  @_ClassValidatorIsDefined()
  @_ClassValidatorIsObject({ each: true })
  @_ClassValidatorValidateNested()
  readonly items!: OrderPublicDto[];

  /**
   * The query string to append to the list path to fetch the next page (e.g. `?limit=20&readAfter=…`). Null on the last page.
   */
  @_CausaRuntimeIsNullable()
  @_ClassValidatorIsString()
  readonly nextPageQuery!: string | null;
}
