// This file was generated by the Causa command line. Do not edit it manually.

import { randomUUID as _CryptoRandomUuid } from 'crypto';
import {
  Book,
  BookAvailability,
  BookEvent,
  BookProjection,
  Money,
  Order,
  OrderBookIndex,
  OrderDocument,
  OrderEvent,
  OrderLine,
  OrderStatus,
  type BookCreatedEvent,
  type BookDeleted,
  type BookDeletedEvent,
  type BookNotDeleted,
  type BookUpdatedEvent,
  type OrderConfirmed,
  type OrderConfirmedEvent,
  type OrderDeleted,
  type OrderFailed,
  type OrderFailedEvent,
  type OrderNotDeleted,
  type OrderPending,
  type OrderPlacedEvent,
  type OrderProcessing,
  type OrderProcessingEvent,
} from './generated.js';

export function makeBookDeleted(data: Partial<BookDeleted> = {}): BookDeleted {
  return new Book({
    deletedAt: new Date(),
    authorName: 'string',
    availability: BookAvailability.Available,
    cost: makeMoney(),
    createdAt: new Date(),
    genre: 'fiction',
    id: _CryptoRandomUuid(),
    isbn: 'string',
    price: makeMoney(),
    title: 'string',
    updatedAt: new Date(),
    ...data,
  }) as BookDeleted;
}

export function makeBookDeletedEvent(
  data: Partial<BookDeletedEvent> = {},
): BookDeletedEvent {
  return new BookEvent({
    data: makeBookDeleted(),
    name: 'bookDeleted',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as BookDeletedEvent;
}

export function makeBookNotDeleted(
  data: Partial<BookNotDeleted> = {},
): BookNotDeleted {
  return new Book({
    deletedAt: null,
    authorName: 'string',
    availability: BookAvailability.Available,
    cost: makeMoney(),
    createdAt: new Date(),
    genre: 'fiction',
    id: _CryptoRandomUuid(),
    isbn: 'string',
    price: makeMoney(),
    title: 'string',
    updatedAt: new Date(),
    ...data,
  }) as BookNotDeleted;
}

export function makeBookCreatedEvent(
  data: Partial<BookCreatedEvent> = {},
): BookCreatedEvent {
  return new BookEvent({
    data: makeBookNotDeleted(),
    name: 'bookCreated',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as BookCreatedEvent;
}

export function makeBookProjection(
  data: Partial<BookProjection> = {},
): BookProjection {
  return new BookProjection({
    availability: BookAvailability.Available,
    createdAt: new Date(),
    deletedAt: null,
    id: _CryptoRandomUuid(),
    title: 'string',
    updatedAt: new Date(),
    ...data,
  });
}

export function makeBookUpdatedEvent(
  data: Partial<BookUpdatedEvent> = {},
): BookUpdatedEvent {
  return new BookEvent({
    data: makeBookNotDeleted(),
    name: 'bookUpdated',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as BookUpdatedEvent;
}

export function makeMoney(data: Partial<Money> = {}): Money {
  return new Money({
    amount: 0,
    currency: 'string',
    ...data,
  });
}

export function makeBook(data: Partial<Book> = {}): Book {
  return new Book({
    authorName: 'string',
    availability: BookAvailability.Available,
    cost: makeMoney(),
    createdAt: new Date(),
    deletedAt: null,
    genre: 'fiction',
    id: _CryptoRandomUuid(),
    isbn: 'string',
    price: makeMoney(),
    title: 'string',
    updatedAt: new Date(),
    ...data,
  });
}

export function makeBookEvent(data: Partial<BookEvent> = {}): BookEvent {
  return new BookEvent({
    data: makeBook(),
    id: _CryptoRandomUuid(),
    name: 'bookCreated',
    producedAt: new Date(),
    ...data,
  });
}

export function makeOrderBookIndex(
  data: Partial<OrderBookIndex> = {},
): OrderBookIndex {
  return new OrderBookIndex({
    book: _CryptoRandomUuid(),
    createdAt: new Date(),
    id: _CryptoRandomUuid(),
    ...data,
  });
}

export function makeOrderConfirmed(
  data: Partial<OrderConfirmed> = {},
): OrderConfirmed {
  return new Order({
    deletedAt: null,
    externalReference: 'string',
    status: OrderStatus.Confirmed,
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    id: _CryptoRandomUuid(),
    lines: [],
    updatedAt: new Date(),
    ...data,
  }) as OrderConfirmed;
}

export function makeOrderConfirmedEvent(
  data: Partial<OrderConfirmedEvent> = {},
): OrderConfirmedEvent {
  return new OrderEvent({
    data: makeOrderConfirmed(),
    name: 'orderConfirmed',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as OrderConfirmedEvent;
}

export function makeOrderDeleted(
  data: Partial<OrderDeleted> = {},
): OrderDeleted {
  return new Order({
    deletedAt: new Date(),
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    externalReference: null,
    id: _CryptoRandomUuid(),
    lines: [],
    status: OrderStatus.Pending,
    updatedAt: new Date(),
    ...data,
  }) as OrderDeleted;
}

export function makeOrderFailed(data: Partial<OrderFailed> = {}): OrderFailed {
  return new Order({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Failed,
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    id: _CryptoRandomUuid(),
    lines: [],
    updatedAt: new Date(),
    ...data,
  }) as OrderFailed;
}

export function makeOrderFailedEvent(
  data: Partial<OrderFailedEvent> = {},
): OrderFailedEvent {
  return new OrderEvent({
    data: makeOrderFailed(),
    name: 'orderFailed',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as OrderFailedEvent;
}

export function makeOrderLine(data: Partial<OrderLine> = {}): OrderLine {
  return new OrderLine({
    book: _CryptoRandomUuid(),
    quantity: 0,
    ...data,
  });
}

export function makeOrder(data: Partial<Order> = {}): Order {
  return new Order({
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    deletedAt: null,
    externalReference: null,
    id: _CryptoRandomUuid(),
    lines: [],
    status: OrderStatus.Pending,
    updatedAt: new Date(),
    ...data,
  });
}

export function makeOrderDocument(
  data: Partial<OrderDocument> = {},
): OrderDocument {
  return new OrderDocument({
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    deletedAt: null,
    id: _CryptoRandomUuid(),
    lines: [],
    status: OrderStatus.Pending,
    updatedAt: new Date(),
    ...data,
  });
}

export function makeOrderEvent(data: Partial<OrderEvent> = {}): OrderEvent {
  return new OrderEvent({
    data: makeOrder(),
    id: _CryptoRandomUuid(),
    name: 'orderPlaced',
    producedAt: new Date(),
    ...data,
  });
}

export function makeOrderNotDeleted(
  data: Partial<OrderNotDeleted> = {},
): OrderNotDeleted {
  return new Order({
    deletedAt: null,
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    externalReference: null,
    id: _CryptoRandomUuid(),
    lines: [],
    status: OrderStatus.Pending,
    updatedAt: new Date(),
    ...data,
  }) as OrderNotDeleted;
}

export function makeOrderPending(
  data: Partial<OrderPending> = {},
): OrderPending {
  return new Order({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Pending,
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    id: _CryptoRandomUuid(),
    lines: [],
    updatedAt: new Date(),
    ...data,
  }) as OrderPending;
}

export function makeOrderPlacedEvent(
  data: Partial<OrderPlacedEvent> = {},
): OrderPlacedEvent {
  return new OrderEvent({
    data: makeOrderPending(),
    name: 'orderPlaced',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as OrderPlacedEvent;
}

export function makeOrderProcessing(
  data: Partial<OrderProcessing> = {},
): OrderProcessing {
  return new Order({
    deletedAt: null,
    externalReference: null,
    status: OrderStatus.Processing,
    createdAt: new Date(),
    customer: _CryptoRandomUuid(),
    id: _CryptoRandomUuid(),
    lines: [],
    updatedAt: new Date(),
    ...data,
  }) as OrderProcessing;
}

export function makeOrderProcessingEvent(
  data: Partial<OrderProcessingEvent> = {},
): OrderProcessingEvent {
  return new OrderEvent({
    data: makeOrderProcessing(),
    name: 'orderProcessing',
    id: _CryptoRandomUuid(),
    producedAt: new Date(),
    ...data,
  }) as OrderProcessingEvent;
}
