// This file was generated by the Causa command line. Do not edit it manually.
import { PUBSUB_EVENT_HANDLER_ID as _CausaRuntimeGooglePubsubEventHandlerId } from '@causa/runtime-google';
import {
  EventBody as _CausaRuntimeEventBody,
  UseEventHandler as _CausaRuntimeUseEventHandler,
} from '@causa/runtime/nestjs';
import {
  Controller as _NestjsCommonController,
  HttpCode as _NestjsCommonHttpCode,
  HttpStatus as _NestjsCommonHttpStatus,
  Post as _NestjsCommonPost,
  type Type as _NestjsCommonType,
} from '@nestjs/common';
import { BookEvent } from '../model/generated.js';

/**
 * The contract for the Catalog event controller.
 */
export interface CatalogEventsContract {
  /**
   * Handles the 'handleBookForProjection' trigger.
   *
   * @param event The event payload.
   */
  handleBookForProjection(event: BookEvent, ...rest: any[]): Promise<void>;
}

/**
 * Decorates a class as a Catalog event controller.
 */
export function AsCatalogEventsController() {
  return function (constructor: _NestjsCommonType<CatalogEventsContract>) {
    _NestjsCommonController('catalog')(constructor);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'handleBookForProjection',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [BookEvent],
        constructor.prototype,
        'handleBookForProjection',
      );
    }
    _NestjsCommonPost('handleBookForProjection')(
      constructor.prototype,
      'handleBookForProjection',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleBookForProjection',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'handleBookForProjection',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleBookForProjection',
      )!,
    );
    _CausaRuntimeUseEventHandler(_CausaRuntimeGooglePubsubEventHandlerId)(
      constructor.prototype,
      'handleBookForProjection',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleBookForProjection',
      )!,
    );
    _CausaRuntimeEventBody()(
      constructor.prototype,
      'handleBookForProjection',
      0,
    );
  };
}
