// This file was generated by the Causa command line. Do not edit it manually.

import { AllowMissing as _CausaRuntimeAllowMissing } from '@causa/runtime';
import { Type as _ClassTransformerType } from 'class-transformer';
import {
  IsDate as _ClassValidatorIsDate,
  IsInt as _ClassValidatorIsInt,
  IsString as _ClassValidatorIsString,
  IsUUID as _ClassValidatorIsUuid,
} from 'class-validator';

/**
 * The path parameters for the `orderCancel` operation.
 */
export class OrderCancelPathParams {
  constructor(init: OrderCancelPathParams) {
    Object.assign(this, init);
  }

  /**
   * The ID of the order to cancel.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;
}

/**
 * The query parameters for the `orderCancel` operation.
 */
export class OrderCancelQueryParams {
  constructor(init: OrderCancelQueryParams) {
    Object.assign(this, init);
  }

  /**
   * The version of the order the client is cancelling.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;
}

/**
 * The path parameters for the `orderGet` operation.
 */
export class OrderGetPathParams {
  constructor(init: OrderGetPathParams) {
    Object.assign(this, init);
  }

  /**
   * The ID of the order.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;
}

/**
 * The query parameters for the `orderList` operation.
 */
export class OrderListQueryParams {
  constructor(init: OrderListQueryParams) {
    Object.assign(this, init);
  }

  /**
   * List a specific customer's orders instead of the caller's.
   * Staff only.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsUuid(undefined)
  readonly customer?: string;

  /**
   * List every order containing this book, across all customers.
   * Staff only. Takes precedence over `customer`.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsUuid(undefined)
  readonly book?: string;

  /**
   * The maximum number of orders to return.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassTransformerType(() => Number)
  @_ClassValidatorIsInt()
  readonly limit?: number;

  /**
   * The cursor returned by a previous page, to read the next page.
   */
  @_CausaRuntimeAllowMissing()
  @_ClassValidatorIsString()
  readonly readAfter?: string;
}

/**
 * The path parameters for the `orderProcess` operation.
 */
export class OrderProcessPathParams {
  constructor(init: OrderProcessPathParams) {
    Object.assign(this, init);
  }

  /**
   * The ID of the order to process.
   */
  @_ClassValidatorIsUuid(undefined)
  readonly id!: string;
}

/**
 * The query parameters for the `orderProcess` operation.
 */
export class OrderProcessQueryParams {
  constructor(init: OrderProcessQueryParams) {
    Object.assign(this, init);
  }

  /**
   * The version of the order the client is processing.
   */
  @_ClassTransformerType(() => Date)
  @_ClassValidatorIsDate()
  readonly updatedAt!: Date;
}
