// This file was generated by the Causa command line. Do not edit it manually.
import {
  CLOUD_SCHEDULER_EVENT_HANDLER_ID as _CausaRuntimeGoogleCloudSchedulerEventHandlerId,
  CLOUD_TASKS_EVENT_HANDLER_ID as _CausaRuntimeGoogleCloudTasksEventHandlerId,
  PUBSUB_EVENT_HANDLER_ID as _CausaRuntimeGooglePubsubEventHandlerId,
} from '@causa/runtime-google';
import {
  EventBody as _CausaRuntimeEventBody,
  UseEventHandler as _CausaRuntimeUseEventHandler,
} from '@causa/runtime/nestjs';
import {
  Controller as _NestjsCommonController,
  HttpCode as _NestjsCommonHttpCode,
  HttpStatus as _NestjsCommonHttpStatus,
  Post as _NestjsCommonPost,
  type Type as _NestjsCommonType,
} from '@nestjs/common';
import { OrderEvent, ReviewReminderTask } from '../model/generated.js';

/**
 * The contract for the Orders event controller.
 */
export interface OrdersEventsContract {
  /**
   * Handles the 'handleOrderForFirestore' trigger.
   *
   * @param event The event payload.
   */
  handleOrderForFirestore(event: OrderEvent, ...rest: any[]): Promise<void>;

  /**
   * Handles the 'handleOrderProcessing' trigger.
   *
   * @param event The event payload.
   */
  handleOrderProcessing(event: OrderEvent, ...rest: any[]): Promise<void>;

  /**
   * Handles the 'expirePendingOrders' trigger.
   *
   * @param event The event payload.
   */
  expirePendingOrders(event: object, ...rest: any[]): Promise<void>;

  /**
   * Handles the 'scheduleReviewReminder' trigger.
   *
   * @param event The event payload.
   */
  scheduleReviewReminder(event: OrderEvent, ...rest: any[]): Promise<void>;

  /**
   * Handles the 'sendReviewReminder' trigger.
   *
   * @param event The event payload.
   */
  sendReviewReminder(event: ReviewReminderTask, ...rest: any[]): Promise<void>;
}

/**
 * Decorates a class as a Orders event controller.
 */
export function AsOrdersEventsController() {
  return function (constructor: _NestjsCommonType<OrdersEventsContract>) {
    _NestjsCommonController('orders')(constructor);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'handleOrderForFirestore',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderEvent],
        constructor.prototype,
        'handleOrderForFirestore',
      );
    }
    _NestjsCommonPost('handleOrderForFirestore')(
      constructor.prototype,
      'handleOrderForFirestore',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderForFirestore',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'handleOrderForFirestore',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderForFirestore',
      )!,
    );
    _CausaRuntimeUseEventHandler(_CausaRuntimeGooglePubsubEventHandlerId)(
      constructor.prototype,
      'handleOrderForFirestore',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderForFirestore',
      )!,
    );
    _CausaRuntimeEventBody()(
      constructor.prototype,
      'handleOrderForFirestore',
      0,
    );

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'handleOrderProcessing',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderEvent],
        constructor.prototype,
        'handleOrderProcessing',
      );
    }
    _NestjsCommonPost('handleOrderProcessing')(
      constructor.prototype,
      'handleOrderProcessing',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderProcessing',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'handleOrderProcessing',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderProcessing',
      )!,
    );
    _CausaRuntimeUseEventHandler(_CausaRuntimeGooglePubsubEventHandlerId)(
      constructor.prototype,
      'handleOrderProcessing',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'handleOrderProcessing',
      )!,
    );
    _CausaRuntimeEventBody()(constructor.prototype, 'handleOrderProcessing', 0);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'expirePendingOrders',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [Object],
        constructor.prototype,
        'expirePendingOrders',
      );
    }
    _NestjsCommonPost('expirePendingOrders')(
      constructor.prototype,
      'expirePendingOrders',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'expirePendingOrders',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'expirePendingOrders',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'expirePendingOrders',
      )!,
    );
    _CausaRuntimeUseEventHandler(
      _CausaRuntimeGoogleCloudSchedulerEventHandlerId,
    )(
      constructor.prototype,
      'expirePendingOrders',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'expirePendingOrders',
      )!,
    );
    _CausaRuntimeEventBody()(constructor.prototype, 'expirePendingOrders', 0);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'scheduleReviewReminder',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderEvent],
        constructor.prototype,
        'scheduleReviewReminder',
      );
    }
    _NestjsCommonPost('scheduleReviewReminder')(
      constructor.prototype,
      'scheduleReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'scheduleReviewReminder',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'scheduleReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'scheduleReviewReminder',
      )!,
    );
    _CausaRuntimeUseEventHandler(_CausaRuntimeGooglePubsubEventHandlerId)(
      constructor.prototype,
      'scheduleReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'scheduleReviewReminder',
      )!,
    );
    _CausaRuntimeEventBody()(
      constructor.prototype,
      'scheduleReviewReminder',
      0,
    );

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'sendReviewReminder',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [ReviewReminderTask],
        constructor.prototype,
        'sendReviewReminder',
      );
    }
    _NestjsCommonPost('sendReviewReminder')(
      constructor.prototype,
      'sendReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'sendReviewReminder',
      )!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'sendReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'sendReviewReminder',
      )!,
    );
    _CausaRuntimeUseEventHandler(_CausaRuntimeGoogleCloudTasksEventHandlerId)(
      constructor.prototype,
      'sendReviewReminder',
      Object.getOwnPropertyDescriptor(
        constructor.prototype,
        'sendReviewReminder',
      )!,
    );
    _CausaRuntimeEventBody()(constructor.prototype, 'sendReviewReminder', 0);
  };
}
