// This file was generated by the Causa command line. Do not edit it manually.
import {
  Body as _NestjsCommonBody,
  Controller as _NestjsCommonController,
  Get as _NestjsCommonGet,
  HttpCode as _NestjsCommonHttpCode,
  HttpStatus as _NestjsCommonHttpStatus,
  Param as _NestjsCommonParam,
  Post as _NestjsCommonPost,
  Query as _NestjsCommonQuery,
  type Type as _NestjsCommonType,
} from '@nestjs/common';
import {
  OrderCreateDto,
  type OrderListDto,
  type OrderPublicDto,
} from '../model/generated.js';
import {
  OrderGetPathParams,
  OrderListQueryParams,
  OrderProcessPathParams,
  OrderProcessQueryParams,
} from './model.js';

/**
 * The contract for the Order API controller.
 */
export interface OrderApiContract {
  /**
   * Lists the authenticated customer's orders, most recent first.
   * Staff may list any customer's orders by passing the `customer` query parameter, or every order containing a given book by passing `book`.
   *
   * @param query The query parameters.
   * @returns The page of orders.
   */
  list(query: OrderListQueryParams, ...rest: any[]): Promise<OrderListDto>;

  /**
   * Places a new order for the authenticated customer.
   * Creates the order in the `pending` status.
   * Each line is validated against the catalogue (the book must exist and be available).
   *
   * @param body The request body.
   * @returns The order was placed successfully.
   */
  place(body: OrderCreateDto, ...rest: any[]): Promise<OrderPublicDto>;

  /**
   * Retrieves a single order.
   * Accessible to the order's customer and to staff.
   *
   * @param params The path parameters.
   * @returns The order was found.
   */
  get(params: OrderGetPathParams, ...rest: any[]): Promise<OrderPublicDto>;

  /**
   * Starts processing a pending order, moving it to `processing`.
   * This in turn begins synchronizing with the third-party provider.
   * The order then becomes `confirmed` or `failed` asynchronously.
   *
   * Only staff may process orders.
   *
   * @param params The path parameters.
   * @param query The query parameters.
   * @returns The order entered processing.
   */
  process(
    params: OrderProcessPathParams,
    query: OrderProcessQueryParams,
    ...rest: any[]
  ): Promise<OrderPublicDto>;
}

/**
 * Decorates a class as a Order API controller.
 */
export function AsOrderApiController() {
  return function (constructor: _NestjsCommonType<OrderApiContract>) {
    _NestjsCommonController('orders')(constructor);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'list',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderListQueryParams],
        constructor.prototype,
        'list',
      );
    }
    _NestjsCommonGet('')(
      constructor.prototype,
      'list',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'list')!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'list',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'list')!,
    );
    _NestjsCommonQuery()(constructor.prototype, 'list', 0);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'place',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderCreateDto],
        constructor.prototype,
        'place',
      );
    }
    _NestjsCommonPost('')(
      constructor.prototype,
      'place',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'place')!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.CREATED)(
      constructor.prototype,
      'place',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'place')!,
    );
    _NestjsCommonBody()(constructor.prototype, 'place', 0);

    if (
      !Reflect.hasOwnMetadata('design:paramtypes', constructor.prototype, 'get')
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderGetPathParams],
        constructor.prototype,
        'get',
      );
    }
    _NestjsCommonGet(':id')(
      constructor.prototype,
      'get',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'get')!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'get',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'get')!,
    );
    _NestjsCommonParam()(constructor.prototype, 'get', 0);

    if (
      !Reflect.hasOwnMetadata(
        'design:paramtypes',
        constructor.prototype,
        'process',
      )
    ) {
      Reflect.defineMetadata(
        'design:paramtypes',
        [OrderProcessPathParams, OrderProcessQueryParams],
        constructor.prototype,
        'process',
      );
    }
    _NestjsCommonPost(':id/process')(
      constructor.prototype,
      'process',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'process')!,
    );
    _NestjsCommonHttpCode(_NestjsCommonHttpStatus.OK)(
      constructor.prototype,
      'process',
      Object.getOwnPropertyDescriptor(constructor.prototype, 'process')!,
    );
    _NestjsCommonParam()(constructor.prototype, 'process', 0);
    _NestjsCommonQuery()(constructor.prototype, 'process', 1);
  };
}
